# `DrugStore.toml` stores shared and synchronized configurations across all platforms.

# The [env] section is used to declare all possible environment variants that
# are used to filter the pills below. The machine configuration `Underdose.toml`
# will look it up and decide which `env`s it possesses.
[env.sys.mac]
[env.sys.linux.arch]
[env.sys.linux.nixos]
[env.school.mac]
[env.home.arch]
# Suppose your `Underdose.toml` has `env = ["mac"]`, then you env will actually
# be `env = ["sys", "mac"]`; if you have `env = ["arch", "school"]`, then you
# env will be `env = ["sys", "linux", "arch", "school"]`. Basically, all nodes
# under `env` are considered effective, and a reference to a child node will
# recursively refer to all parents within the chain.


# The [pill] section is used to store the pills that are going to be distributed.

# A simple pill about the nvim configuration. All machines follow the same
# configuration, and under the same path, so there is no subtlety.
[[pill]]
name = "nvim"
[[pill.drip]]
site = "~/.config/nvim"
[[pill.drip.arrow]]
site = "."
src.link = "."

# A pill about the awesome configuration, stored in a git submodule.
# Note that the submodule will be cloned to the drugstore, and the site should be
# a link or copy without the .git directory depending on root.mode.
[[pill]]
name = "awesome"
[[pill.drip]]
# only makes sense under linux
env = ["linux"]
# You can decide where to put on site and in the repo
site = "~/.config/awesome"
[[pill.drip.arrow]]
site = "."
src.git = "git@github.com:path/to/awesome_conf.git"

# A pill on emacs configuration but with different distribution path. The root
# and stem are updated as `underdose` read through the pill and update according
# to the matching result of env. Observe how the `drip`s drip through.
[[pill]]
name = "emacs"
[[pill.drip]]
repo = "emacs"
[[pill.drip.arrow]]
# same arrow...
site = "init.el"
src.link = "init.el"
# ...but different sites...
[[pill.drip]]
env = ["linux"]
site = "~/.config/emacs"
# ...on different envs.
[[pill.drip]]
env = ["mac"]
site = "~/.emacs.d"

# A pill with two different configurations on the same software, but share same
# common files.
[[pill]]
name = "zsh"
[[pill.drip]]
site = "~"
repo = "zsh"
[[pill.drip.arrow]]
site = ".zshrc"
src.link = ".zshrc"
[[pill.drip.arrow]]
site = ".zshenv"
src.link = ".zshenv"
[[pill.drip]]
env = ["mac"]
[[pill.drip.arrow]]
site = ".zsh_aliases"
src.link = ".zsh_aliases_mac"
[[pill.drip]]
env = ["linux"]
[[pill.drip.arrow]]
site = ".zsh_aliases"
src.link = ".zsh_aliases_linux"
# As for the mapping, it's just the spec requires an implementation in this
# repo, and it will be renamed when pouring onto the machine as the LHS. This
# time all linux machines referred to.


# After carefully editing the rest of the file, remove this line and below to
# make this `DrugStore.toml` file valid and ready to use.
[tutorial]
