# DO NOT DELETE ANY OPTION because it's better to keep things obvious.

# Describe the tag set of the machine which forms the `env`.
# See `DrugStore.toml` for a full example.
env = ["arch"]

[repo]
# Name of this machine's configuration.
name = "archan"
# Path to the local drugstore repo.
local = "path/to/your/local/drugstore/repo"

# After carefully editing the rest of the file, remove this line and below to
# make this `Underdose.toml` file valid and ready to use.
[tutorial]
