# DO NOT DELETE ANY OPTION because it's better to keep things obvious.

# (unimportant) unique name only for building dir
name = "archan"
# see `DrugStore.toml` for a full example of `env`
env = ["arch"]
# path to the local drugstore repo
repo = "path/to/your/local/drugstore/repo/"


[defaults]

# sync <: "copy" | "link"
sync = "copy"

# recent versions to keep
undo = 10

# global ignore
ignore = [".git/"]

[features]

# git submodule support: drip level submodule detection; automatically moves
# git repo to the drugstore or clone it if not present
submodule = true

# turn on glob patterns everywhere
glob = false

# sync local symlinks in settings (not implemented)
symlink = false

[cleanup.empty_dir]
site = false
repo = true


# After carefully editing the rest of the file, remove this line and below to
# make this `Underdose.toml` file valid and ready to use.
[tutorial.underdose]