# DO NOT DELETE ANY OPTION because it's better to keep things obvious.

# see `DrugStore.toml` for a full example of `env`
env = ["arch"]

# path to the local drugstore repos
[repo]
# (unimportant) unique name only for building dir
# The first entry is the default repo
#archan = "path/to/your/local/drugstore/repo"


[defaults]

# sync <: "link" | "copy"
sync = "link"

# path to cache dir; remove entry to use the default
#cache = "path/to/your/cache/dir"

# recent pill-wise versions to keep; remove entry for unlimited
#undo = 100

# global ignore
ignore = ["**/.git"]

[features]

# collect local `Underdose.toml` to the drugstore/.underdose dir
overdose = true

# git submodule support: drip level submodule detection; automatically clones
# git repo to the drugstore if not present
submodule = true

# sync local symlinks in settings (not implemented)
symlink = false

[cleanup.empty_dir]
site = false
repo = false


# After carefully editing the rest of the file, remove this line and below to
# make this `Underdose.toml` file valid and ready to use.
[tutorial]