complete -c underdose -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c underdose -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c underdose -n "__fish_use_subcommand" -f -a "init" -d 'Initialize on a new machine, working from drugstore repo'
complete -c underdose -n "__fish_use_subcommand" -f -a "config" -d 'Configure the machine'
complete -c underdose -n "__fish_use_subcommand" -f -a "where" -d 'Shows all path information available'
complete -c underdose -n "__fish_use_subcommand" -f -a "sync" -d 'Make a dream on the machine, and pour if possible'
complete -c underdose -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c underdose -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c underdose -n "__fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c underdose -n "__fish_seen_subcommand_from where" -s h -l help -d 'Print help'
complete -c underdose -n "__fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c underdose -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from where; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize on a new machine, working from drugstore repo'
complete -c underdose -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from where; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "config" -d 'Configure the machine'
complete -c underdose -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from where; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "where" -d 'Shows all path information available'
complete -c underdose -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from where; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "sync" -d 'Make a dream on the machine, and pour if possible'
complete -c underdose -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from where; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
